import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import { AUTH_API, USER_API } from "./services/api";
import "./index.css";

function App() {
  const [authMode, setAuthMode] = useState("login");
  const [form, setForm] = useState({ name: "", email: "", password: "" });

  const [profileForm, setProfileForm] = useState({
    name: "",
    platform: "",
    username: "",
  });

  const [user, setUser] = useState(JSON.parse(localStorage.getItem("user")));
  const [leaderboard, setLeaderboard] = useState([]);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);

  const [searchName, setSearchName] = useState("");
  const [searchedProfile, setSearchedProfile] = useState(null);

  const [aiInsights, setAiInsights] = useState("");
  const [insightLoading, setInsightLoading] = useState(false);

  const [aiRecommendations, setAiRecommendations] = useState("");
  const [recommendLoading, setRecommendLoading] = useState(false);

  const [compareForm, setCompareForm] = useState({ user1: "", user2: "" });
  const [comparison, setComparison] = useState(null);

  const getRankBadge = (score) => {
    if (score >= 3000) return "Elite Coder";
    if (score >= 1500) return "Advanced Coder";
    if (score >= 700) return "Intermediate Coder";
    if (score > 0) return "Beginner Coder";
    return "Not Ranked";
  };

  const getStrengthPercent = (score) => {
    return Math.min(Math.round((score / 3000) * 100), 100);
  };

  const downloadPDFReport = (profile) => {
    const doc = new jsPDF();

    const score = profile.total_score || 0;
    const rank = getRankBadge(score);
    const strength = getStrengthPercent(score);
    const platforms = profile.platforms || {};

    let y = 20;

    doc.setFontSize(20);
    doc.text("Code Profile Analyzer Report", 20, y);

    y += 15;
    doc.setFontSize(12);
    doc.text(`Name: ${profile.name}`, 20, y);

    y += 8;
    doc.text(`Total Score: ${score}`, 20, y);

    y += 8;
    doc.text(`Rank: ${rank}`, 20, y);

    y += 8;
    doc.text(`Profile Strength: ${strength}%`, 20, y);

    y += 15;
    doc.setFontSize(15);
    doc.text("Platform Stats", 20, y);

    doc.setFontSize(11);

    y += 10;
    doc.text(
      `Codeforces: ${platforms.codeforces?.handle || "N/A"} | Rating: ${
        platforms.codeforces?.rating || "N/A"
      } | Solved: ${platforms.codeforces?.solved_count || 0}`,
      20,
      y
    );

    y += 8;
    doc.text(
      `LeetCode: ${platforms.leetcode?.username || "N/A"} | Solved: ${
        platforms.leetcode?.total_solved || 0
      } | Easy: ${platforms.leetcode?.easy || 0} | Medium: ${
        platforms.leetcode?.medium || 0
      } | Hard: ${platforms.leetcode?.hard || 0}`,
      20,
      y
    );

    y += 8;
    doc.text(
      `GitHub: ${platforms.github?.username || "N/A"} | Repos: ${
        platforms.github?.public_repos || 0
      } | Followers: ${platforms.github?.followers || 0}`,
      20,
      y
    );

    y += 8;
    doc.text(
      `GFG: ${platforms.gfg?.username || "N/A"} | Solved: ${
        platforms.gfg?.total_solved || 0
      } | Coding Score: ${platforms.gfg?.coding_score || 0}`,
      20,
      y
    );

    y += 8;
    doc.text(
      `HackerRank: ${platforms.hackerrank?.username || "N/A"}`,
      20,
      y
    );

    y += 8;
    doc.text(
      `CodeChef: ${platforms.codechef?.username || "N/A"} | Rating: ${
        platforms.codechef?.rating || "N/A"
      }`,
      20,
      y
    );

    y += 15;
    doc.setFontSize(15);
    doc.text("AI Skill Recommendations", 20, y);

    doc.setFontSize(10);

    const recommendationText =
      aiRecommendations ||
      "Generate AI Skill Recommendations from the dashboard before downloading for detailed AI guidance.";

    const lines = doc.splitTextToSize(recommendationText, 170);

    lines.forEach((line) => {
      y += 7;
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 20, y);
    });

    y += 15;
    doc.setFontSize(10);
    doc.text("Generated by Code Profile Analyzer", 20, y);

    doc.save(`${profile.name}_Coding_Profile_Report.pdf`);
  };

  const copyPublicProfileLink = (profile) => {
    const link = `${window.location.origin}/profile/${profile.name.replaceAll(
      " ",
      "-"
    )}`;

    navigator.clipboard.writeText(link);
    alert("Public profile link copied. Public page will be added in next step.");
  };

  const fetchLeaderboard = async () => {
    try {
      const res = await USER_API.get("/leaderboard");
      setLeaderboard(res.data.leaderboard || []);
    } catch (error) {
      console.log(error);
    }
  };

  const handleAuth = async (e) => {
    e.preventDefault();

    try {
      const endpoint = authMode === "login" ? "/login" : "/signup";
      const res = await AUTH_API.post(endpoint, form);

      if (res.data.error) {
        alert(res.data.error);
        return;
      }

      if (authMode === "signup") {
        alert("Signup successful. Please login.");
        setAuthMode("login");
        setForm({ name: "", email: "", password: "" });
        return;
      }

      const loggedUser = {
        name: res.data.name,
        email: form.email,
      };

      localStorage.setItem("user", JSON.stringify(loggedUser));
      localStorage.setItem("token", res.data.access_token);
      setUser(loggedUser);
    } catch (error) {
      console.log(error);
      alert("Authentication failed");
    }
  };

  const addProfile = async (e) => {
    e.preventDefault();

    const payload = {
      name: profileForm.name,
      [profileForm.platform]: profileForm.username,
    };

    try {
      setLoading(true);
      setMessage("");

      const res = await USER_API.post("/add", payload);

      if (res.data.error) {
        setMessage(res.data.error);
        return;
      }

      setMessage(res.data.message);
      setProfileForm({ name: "", platform: "", username: "" });
      fetchLeaderboard();
    } catch (error) {
      console.log(error);
      setMessage("Something went wrong");
    } finally {
      setLoading(false);
    }
  };

  const searchProfile = async () => {
    if (!searchName.trim()) {
      alert("Enter profile name");
      return;
    }

    try {
      const res = await USER_API.get(`/profile/${searchName}`);

      if (res.data.error) {
        alert(res.data.error);
        setSearchedProfile(null);
        return;
      }

      setSearchedProfile(res.data);
      setAiInsights("");
      setAiRecommendations("");
    } catch (error) {
      console.log(error);
      alert("Search failed");
    }
  };

  const fetchInsights = async (name) => {
    try {
      setInsightLoading(true);
      setAiInsights("");

      const res = await USER_API.get(`/insights/${name}`);

      if (res.data.error) {
        alert(res.data.error);
        return;
      }

      setAiInsights(res.data.insights);
    } catch (error) {
      console.log(error);
      alert("AI insights failed");
    } finally {
      setInsightLoading(false);
    }
  };

  const fetchAIRecommendations = async (name) => {
    try {
      setRecommendLoading(true);
      setAiRecommendations("");

      const res = await USER_API.get(`/recommendations/${name}`);

      if (res.data.error) {
        alert(res.data.error);
        return;
      }

      setAiRecommendations(res.data.recommendations);
    } catch (error) {
      console.log(error);
      alert("AI recommendations failed");
    } finally {
      setRecommendLoading(false);
    }
  };

  const compareUsers = async (e) => {
    e.preventDefault();

    try {
      const res = await USER_API.get(
        `/compare/${compareForm.user1}/${compareForm.user2}`
      );

      if (res.data.error) {
        alert(res.data.error);
        setComparison(null);
        return;
      }

      setComparison(res.data);
    } catch (error) {
      console.log(error);
      alert("Compare failed");
    }
  };

  const deleteUser = async (name) => {
    const confirmDelete = window.confirm(`Delete ${name}?`);
    if (!confirmDelete) return;

    try {
      const res = await USER_API.delete(`/delete/${name}`);

      if (res.data.error) {
        alert(res.data.error);
        return;
      }

      alert(res.data.message);
      fetchLeaderboard();
      setSearchedProfile(null);
      setComparison(null);
      setAiInsights("");
      setAiRecommendations("");
    } catch (error) {
      console.log(error);
      alert("Delete failed");
    }
  };

  const logout = () => {
    localStorage.removeItem("user");
    localStorage.removeItem("token");
    setUser(null);
  };

  useEffect(() => {
    if (user) fetchLeaderboard();
  }, [user]);

  if (!user) {
    return (
      <div className="auth-page">
        <div className="auth-card">
          <div className="auth-badge">🚀 Coding Analytics</div>

          <h1>Code Profile Analyzer</h1>

          <p className="subtitle">
            Skill ranking system for competitive programmers
          </p>

          <h2>{authMode === "login" ? "Welcome Back" : "Create Account"}</h2>

          <form onSubmit={handleAuth} className="form">
            {authMode === "signup" && (
              <input
                type="text"
                placeholder="Full Name"
                value={form.name}
                onChange={(e) => setForm({ ...form, name: e.target.value })}
                required
              />
            )}

            <input
              type="email"
              placeholder="Email Address"
              value={form.email}
              onChange={(e) => setForm({ ...form, email: e.target.value })}
              required
            />

            <input
              type="password"
              placeholder="Password"
              value={form.password}
              onChange={(e) => setForm({ ...form, password: e.target.value })}
              required
            />

            <div className="login-btn-wrapper">
              <button type="submit" className="primary-btn">
                {authMode === "login" ? "Login" : "Create Account"}
              </button>
            </div>
          </form>

          <button
            className="link-btn"
            onClick={() =>
              setAuthMode(authMode === "login" ? "signup" : "login")
            }
          >
            {authMode === "login"
              ? "Create new account"
              : "Already have an account? Login"}
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="app-page">
      <header className="topbar">
        <div>
          <h1>Code Profile Analyzer</h1>
          <p>Welcome, {user.name}</p>
        </div>

        <button onClick={logout} className="danger-btn">
          Logout
        </button>
      </header>

      <main className="container">
        <section className="grid-two">
          <div className="card">
            <h2>Add / Update Coding Profile</h2>

            <form onSubmit={addProfile} className="form">
              <input
                placeholder="Profile Name e.g. Ayush"
                value={profileForm.name}
                onChange={(e) =>
                  setProfileForm({ ...profileForm, name: e.target.value })
                }
                required
              />

              <select
                value={profileForm.platform}
                onChange={(e) =>
                  setProfileForm({ ...profileForm, platform: e.target.value })
                }
                required
              >
                <option value="">Select Platform</option>
                <option value="codeforces">Codeforces</option>
                <option value="leetcode">LeetCode</option>
                <option value="github">GitHub</option>
                <option value="gfg">GeeksforGeeks</option>
                <option value="hackerrank">HackerRank</option>
                <option value="codechef">CodeChef</option>
              </select>

              <input
                placeholder="Platform Username"
                value={profileForm.username}
                onChange={(e) =>
                  setProfileForm({ ...profileForm, username: e.target.value })
                }
                required
              />

              <button className="primary-btn" disabled={loading}>
                {loading ? "Analyzing..." : "Analyze Profile"}
              </button>
            </form>

            {message && <p className="success-msg">{message}</p>}
          </div>

          <div className="card">
            <h2>Leaderboard</h2>

            <div className="leaderboard-list">
              {leaderboard.length === 0 && (
                <p className="muted">No profiles added yet.</p>
              )}

              {leaderboard.map((item, index) => (
                <div key={item._id} className="leaderboard-card">
                  <div>
                    <h3>
                      #{index + 1} {item.name}
                    </h3>

                    <p className="score">Score: {item.total_score || 0}</p>

                    <p className="rank-badge">
                      {getRankBadge(item.total_score || 0)}
                    </p>

                    <button
                      onClick={() => deleteUser(item.name)}
                      className="small-danger-btn"
                    >
                      Delete
                    </button>
                  </div>

                  <div className="platform-list">
                    <p>CF: {item.platforms?.codeforces?.handle || "N/A"}</p>
                    <p>LC: {item.platforms?.leetcode?.username || "N/A"}</p>
                    <p>GH: {item.platforms?.github?.username || "N/A"}</p>
                    <p>GFG: {item.platforms?.gfg?.username || "N/A"}</p>
                    <p>HR: {item.platforms?.hackerrank?.username || "N/A"}</p>
                    <p>CC: {item.platforms?.codechef?.username || "N/A"}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="grid-two">
          <div className="card">
            <h2>Search Profile</h2>

            <div className="search-row">
              <input
                placeholder="Enter profile name"
                value={searchName}
                onChange={(e) => setSearchName(e.target.value)}
              />

              <button onClick={searchProfile} className="green-btn">
                Search
              </button>
            </div>

            {searchedProfile && (
              <div className="result-box">
                <h3>{searchedProfile.name}</h3>

                <p className="score">
                  Total Score: {searchedProfile.total_score || 0}
                </p>

                <p className="rank-badge">
                  {getRankBadge(searchedProfile.total_score || 0)}
                </p>

                <div className="strength-box">
                  <div className="strength-top">
                    <span>Profile Strength</span>
                    <strong>
                      {getStrengthPercent(searchedProfile.total_score || 0)}%
                    </strong>
                  </div>

                  <div className="strength-bar">
                    <div
                      className="strength-fill"
                      style={{
                        width: `${getStrengthPercent(
                          searchedProfile.total_score || 0
                        )}%`,
                      }}
                    ></div>
                  </div>
                </div>

                <div className="action-row">
                  <button
                    className="primary-btn"
                    onClick={() => downloadPDFReport(searchedProfile)}
                  >
                    Download Resume Report
                  </button>

                  <button
                    className="green-btn"
                    onClick={() => copyPublicProfileLink(searchedProfile)}
                  >
                    Copy Public Profile Link
                  </button>
                </div>

                <div className="recommend-box">
                  <h3>🤖 AI Skill Recommendations</h3>

                  <button
                    className="purple-btn ai-btn"
                    onClick={() =>
                      fetchAIRecommendations(searchedProfile.name)
                    }
                    disabled={recommendLoading}
                  >
                    {recommendLoading
                      ? "Generating Recommendations..."
                      : "Generate AI Skill Recommendations"}
                  </button>

                  {aiRecommendations && (
                    <div className="recommend-text">
  {aiRecommendations}
</div>
                  )}
                </div>

                <div className="analytics-grid">
                  <AnalyticsCard
                    title="Codeforces"
                    icon="⚡"
                    logo="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/codeforces.svg"
                    value={
                      searchedProfile.platforms?.codeforces?.rating || "N/A"
                    }
                    label="Current Rating"
                    extra={`Solved: ${
                      searchedProfile.platforms?.codeforces?.solved_count || 0
                    }`}
                  />

                  <AnalyticsCard
                    title="LeetCode"
                    icon="🧩"
                    logo="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/leetcode.svg"
                    value={
                      searchedProfile.platforms?.leetcode?.total_solved || 0
                    }
                    label="Total Solved"
                    extra={`Easy ${
                      searchedProfile.platforms?.leetcode?.easy || 0
                    } | Medium ${
                      searchedProfile.platforms?.leetcode?.medium || 0
                    } | Hard ${
                      searchedProfile.platforms?.leetcode?.hard || 0
                    }`}
                  />

                  <AnalyticsCard
                    title="GitHub"
                    icon="💻"
                    logo="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg"
                    value={
                      searchedProfile.platforms?.github?.public_repos || 0
                    }
                    label="Public Repos"
                    extra={`Followers: ${
                      searchedProfile.platforms?.github?.followers || 0
                    }`}
                  />

                  <AnalyticsCard
                    title="GeeksforGeeks"
                    icon="📚"
                    logo="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/geeksforgeeks.svg"
                    value={searchedProfile.platforms?.gfg?.total_solved || 0}
                    label="Problems Solved"
                    extra={`Coding Score: ${
                      searchedProfile.platforms?.gfg?.coding_score || 0
                    }`}
                  />

                  <AnalyticsCard
                    title="HackerRank"
                    icon="🎯"
                    logo="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/hackerrank.svg"
                    value={
                      searchedProfile.platforms?.hackerrank?.username || "N/A"
                    }
                    label="Username"
                    extra={`Status: ${
                      searchedProfile.platforms?.hackerrank?.status ||
                      "Connected"
                    }`}
                  />

                  <AnalyticsCard
                    title="CodeChef"
                    icon="👨‍🍳"
                    logo="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/codechef.svg"
                    value={
                      searchedProfile.platforms?.codechef?.rating || "N/A"
                    }
                    label="Rating"
                    extra={`Stars: ${
                      searchedProfile.platforms?.codechef?.stars || "N/A"
                    }`}
                  />
                </div>

                <button
                  className="purple-btn ai-btn"
                  onClick={() => fetchInsights(searchedProfile.name)}
                  disabled={insightLoading}
                >
                  {insightLoading
                    ? "Generating Insights..."
                    : "Generate AI Insights"}
                </button>

                {aiInsights && (
                  <div className="ai-insights-box">
                    <h3>🤖 AI Insights</h3>
                    <div className="recommend-text">
  {aiInsights}
</div>
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="card">
            <h2>Compare Users</h2>

            <form onSubmit={compareUsers} className="form">
              <input
                placeholder="First Profile Name"
                value={compareForm.user1}
                onChange={(e) =>
                  setCompareForm({ ...compareForm, user1: e.target.value })
                }
                required
              />

              <input
                placeholder="Second Profile Name"
                value={compareForm.user2}
                onChange={(e) =>
                  setCompareForm({ ...compareForm, user2: e.target.value })
                }
                required
              />

              <button className="purple-btn">Compare</button>
            </form>

            {comparison && (
              <div className="result-box">
                <h3 className="winner">Winner: {comparison.winner}</h3>

                <div className="compare-grid">
                  <div className="mini-card">
                    <h4>{comparison.user1.name}</h4>
                    <p>Score: {comparison.user1.score}</p>
                    <p className="rank-badge">
                      {getRankBadge(comparison.user1.score || 0)}
                    </p>
                  </div>

                  <div className="mini-card">
                    <h4>{comparison.user2.name}</h4>
                    <p>Score: {comparison.user2.score}</p>
                    <p className="rank-badge">
                      {getRankBadge(comparison.user2.score || 0)}
                    </p>
                  </div>
                </div>
              </div>
            )}
          </div>
        </section>
      </main>
    </div>
  );
}

function AnalyticsCard({ title, icon, logo, value, label, extra }) {
  return (
    <div className="analytics-card">
      <div className="analytics-header">
        <img src={logo} alt={title} className="platform-logo" />
        <div className="analytics-icon">{icon}</div>
      </div>

      <h4>{title}</h4>
      <p className="analytics-value">{value}</p>
      <span>{label}</span>
      <small>{extra}</small>
    </div>
  );
}

export default App;